AWSTemplateFormatVersion: "2010-09-09"
Description: ALB Template

# Input Parameters
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
    Description: Project Code
### ALB SSL Listener Policy ###
  ALBSSLPolicy:
    Type: String
    Default: ELBSecurityPolicy-2016-08
    Description: ALB SSL Listener Policy

Resources:
# Application Load balancer
  ### ALB ###
  ALB: 
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties: 
      Name: !Sub "${PJPrefix}-alb"
      Scheme: "internet-facing"
      LoadBalancerAttributes: 
        - Key: "deletion_protection.enabled"
          Value: false
        - Key: "idle_timeout.timeout_seconds"
          Value: 4000
      SecurityGroups:
        - { "Fn::ImportValue": !Sub "${PJPrefix}-alb-sg" }
      Subnets: 
        - { "Fn::ImportValue": !Sub "${PJPrefix}-public-subnet-a" }
        - { "Fn::ImportValue": !Sub "${PJPrefix}-public-subnet-c" }

### ALB Listener ###
  ALBListenerHTTP: 
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - RedirectConfig:
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_301
          Type: redirect
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP      
  
  ALBListenerHTTPS:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      Certificates:
        - CertificateArn: !ImportValue ACMApNorthEast
      DefaultActions:
        - TargetGroupArn: { "Fn::ImportValue": !Sub "${PJPrefix}-tg" }
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      SslPolicy: !Ref ALBSSLPolicy

# Output Parameters:
### ALB ###
Outputs:
  ALB:
    Value: !Ref ALB
    Export:
      Name: !Sub "${PJPrefix}-alb"
  ALBDNSName:
    Value: !GetAtt "ALB.DNSName"
    Export:
      Name: !Sub "${PJPrefix}-ALBDNSName"
  ALBHostedZoneId:
    Value: !GetAtt "ALB.CanonicalHostedZoneID"
    Export:
      Name: !Sub "${PJPrefix}-ALBHostedZoneId"