AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Template

# Input Parameters
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
    Description: Project Code
### Environment ###
  Environment:
    Type: String
    Default: stg,prod
    Description: Environment

### Resources ###
Resources: 
### S3 ###
  S3BucketForCFAccessLog:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${PJPrefix}-${Environment}-cf-accesslog-bucket"
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-${Environment}-cf-accesslog-bucket"

  BucketPolicyForCFAccessLog:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3BucketForCFAccessLog
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${S3BucketForCFAccessLog}/*"
          Principal: '*'
  
  S3BucketForWaflog:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "aws-waf-logs-${PJPrefix}-${Environment}"
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "aws-waf-logs-${PJPrefix}-${Environment}"

  BucketPolicyForWaflog:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3BucketForWaflog
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${S3BucketForWaflog}/*"
          Principal: '*'

# Output Parameters:
Outputs:
### S3 for CloudFront ###
  S3BucketForCFAccessLog:
    Value: !Ref S3BucketForCFAccessLog
    Export:
      Name: !Sub "${PJPrefix}-${Environment}-cf-accesslog-bucket"
### S3 for WAF ###
  S3BucketForWaflog:
    Value: !Ref S3BucketForWaflog
    Export:
      Name: !Sub "aws-waf-logs-${PJPrefix}-${Environment}"