AWSTemplateFormatVersion: "2010-09-09"
Description: Web ACL Template

# Input Parameters
Parameters:
### Project Prefix ###
  PJPrefix:
    Type: String
    Description: Project Code
### Web ACl Scope ###
  Scope:
    Type: String
    Default: CLOUDFRONT
    AllowedValues:
      - REGIONAL
      - CLOUDFRONT
    Description: "Select in the scope of waf(REGIONAL or CLOUDFRONT)"
### IP Set Addresses ###
  IPv4A:
    Type: String
    Default: 10.0.0.0/16
    Description: Set IP addresses for WAF IPset
  IPv4B:
    Type: String
    Default: 172.16.0.0/16
    Description: Set IP addresses for WAF IPset
  IPv4C:
    Type: String
    Default: 192.168.0.0/16
    Description: Set IP addresses for WAF IPset


### Resources ###
Resources: 
### WAF v2 ###
  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties: 
      Name: !Sub "${PJPrefix}-web-acl"
      Scope: !Ref Scope
      DefaultAction:
        Block: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: !Sub ${PJPrefix}-web-acl
      Rules:
        - Name: WAFIPsetRule
          Priority: 0
          Action:
            Allow: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFIPSet.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: WAFIPsetRule
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: NoUserAgent_HEADER
                - Name: UserAgent_BadBots_HEADER
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_Cookie_HEADER
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_URIPATH
                - Name: EC2MetaDataSSRF_BODY
                - Name: EC2MetaDataSSRF_COOKIE
                - Name: EC2MetaDataSSRF_URIPATH
                - Name: EC2MetaDataSSRF_QUERYARGUMENTS
                - Name: GenericLFI_QUERYARGUMENTS
                - Name: GenericLFI_URIPATH
                - Name: GenericLFI_BODY
                - Name: RestrictedExtensions_URIPATH
                - Name: RestrictedExtensions_QUERYARGUMENTS
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_BODY
                - Name: GenericRFI_URIPATH
                - Name: CrossSiteScripting_COOKIE
                - Name: CrossSiteScripting_QUERYARGUMENTS
                - Name: CrossSiteScripting_BODY
                - Name: CrossSiteScripting_URIPATH
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
  WAFLogConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      LogDestinationConfigs:
        - !Sub "arn:aws:s3:::aws-waf-logs-${PJPrefix}"
      ResourceArn: !GetAtt WebAcl.Arn
  WAFIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub "${PJPrefix}-WAF-IPset"
      Scope: !Ref Scope
      IPAddressVersion: IPV4
      Addresses:
          - 10.0.0.0/16
          - 192.168.0.0/24
          - 1.1.1.0/32
  